name: Feature Request
description: Suggest an idea for this project
title: "[Enhancement] Title"
labels: ["enhancement"]
assignees:
  - TheWisker
body:
  - type: markdown
    attributes:
      value: |
        # Shikai Feature Request
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: explanation
    attributes:
      label: Explanation
      description: Clear and concise description of the feature request
      placeholder: I would like that ... is added and ... is changed because ...
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Expected Behavior
      description: Clear and concise description of what you expected to happen
      placeholder: I would like that when I ... ... happens
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Clear and concise description of any alternative solutions or features you've considered
      placeholder: I have also considered ... and it can also be achieved with ...
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheWisker/Shikai/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true