name: AUR Update Git
run-name: AUR package update by ${{ github.actor }} push
on:
  push:
    branches:
      - 'master'
permissions:
  contents: write
concurrency:
  group: "aur"
  cancel-in-progress: false
jobs:
  aur-update-git:
    environment:
      name: aur-packages
    runs-on: ubuntu-latest 
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: AUR Update Git
        uses: TheWisker/aur-update-git@master
        with:
          aur_key: ${{ secrets.AUR_KEY }}
          username: TheWisker
          email: TheWisker@protonmail.com