name: Deploy Pages
run-name: Page deployment by ${{ github.actor }}
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
permissions:
  pages: write
  contents: read
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
          submodules: 'recursive'
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4