name: Deploy Pages
run-name: Page deployment by ${{ github.actor }}
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1